"""
    SCPR.Server.REST

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.double_range import DoubleRange
from openapi_client.model.scpr_model_type import SCPRModelType
from openapi_client.model.shape_constraint import ShapeConstraint
from openapi_client.model.version import Version
globals()['DoubleRange'] = DoubleRange
globals()['SCPRModelType'] = SCPRModelType
globals()['ShapeConstraint'] = ShapeConstraint
globals()['Version'] = Version
from openapi_client.model.scpr_parameters import SCPRParameters


class TestSCPRParameters(unittest.TestCase):
    """SCPRParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSCPRParameters(self):
        """Test SCPRParameters"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SCPRParameters()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
