"""
    SCPR.Server.REST

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.scpr_model_type import SCPRModelType


class TestSCPRModelType(unittest.TestCase):
    """SCPRModelType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSCPRModelType(self):
        """Test SCPRModelType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SCPRModelType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
