"""
    SCPR.Server.REST

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.double_range import DoubleRange


class TestDoubleRange(unittest.TestCase):
    """DoubleRange unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDoubleRange(self):
        """Test DoubleRange"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DoubleRange()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
