"""
    SCPR.Server.REST

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.scpr_api import SCPRApi  # noqa: E501


class TestSCPRApi(unittest.TestCase):
    """SCPRApi unit test stubs"""

    def setUp(self):
        self.api = SCPRApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_train(self):
        """Test case for train

        """
        pass


if __name__ == '__main__':
    unittest.main()
