"""
    SCPR.Server.REST

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.scpr_parameters import SCPRParameters
globals()['SCPRParameters'] = SCPRParameters
from openapi_client.model.training_request import TrainingRequest


class TestTrainingRequest(unittest.TestCase):
    """TrainingRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTrainingRequest(self):
        """Test TrainingRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TrainingRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
